import * as React from "react";
 import Banner from "../components/locationDetails/banner";
import Footer from "../components/layouts/footer";
import Header from "../components/layouts/header";
import BreadCrumbs from "../components/layouts/BreadCrumbs";
import GetDirection from "../components/commons/GetDirection";
// import { stagingBaseUrl } from "../constants";
import Address from "../components/commons/Address";
import Phone from "../components/commons/phone";
import favicon from "../images/favicon.png"
import OpenCloseStatus from "../components/commons/OpenCloseStatus";
import bannerImage from "../images/francepare1.png";
import "../index.css";
var currentUrl = "";
import "../index.css";
import {
  Template,
  GetPath,
  GetRedirects,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";

export const config: TemplateConfig = {
  stream: {
    $id: "city",
    filter: {
      savedFilterIds: ["dm_franceparebrise-directory_address_city"],
    },
    fields: [
      "id",
      "uid",
      "meta",
      "name",
      "c_addressRegionDisplayName",
      "slug",
      "c_labels",
      "c_metaTags",
      "c_ogMetaTag",
      "dm_directoryParents.name",
      "dm_directoryParents.slug",
      "dm_directoryParents.meta.entityType",
      "dm_directoryChildren.name",
      "dm_directoryChildren.slug",
      "dm_directoryChildren.dm_directoryChildrenCount",
      "dm_directoryChildren.address",
      "dm_directoryChildren.hours",
      "dm_directoryChildren.mainPhone",
      "dm_directoryChildren.yextDisplayCoordinate",

    ],
    localization: {
      locales: ["fr"],
      primary: false,
    },
  },
};

export const getPath: GetPath<TemplateProps> = ({ document }) => {
  var slug:any="";
  document.dm_directoryParents.map((i:any)=>{
if(i.meta.entityType.id=="ce_country"){
slug=i.slug

}
else if(i.meta.entityType.id=="ce_region"){
  slug=`${slug}/${i.slug}`
}
  })
  return `${slug}/${document.slug}.html`;
};
const metersToMiles = (kilometers: number) => {
  const miles = kilometers * 0.62137119;
  return miles.toFixed(2);
};
export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({
  relativePrefixToRoot,
  path,
  document,
}): HeadConfig => {
  return {
    title: document.name,
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "link",
        attributes: {
          rel: "icon",
          type: "image/x-icon",
          href: favicon,
        },
      },
    {
      type: "meta",
      attributes: {
        description: "This site was generated by the Yext SSG",
      },
    },
    {
      type: "meta",
      attributes: {
        name: "description",
        content: `${document.c_metaTags.description ? document.c_metaTags.description : ""
          }`,
      },
    },

    {
      type: "meta",
      attributes: {
        name: "title",
        content: `${document.c_metaTags.title ? document.c_metaTags.title : ""}`,
      },
    },
    {
      type: "meta",
      attributes: {
        name: "author",
        content: `${document.c_metaTags.author ? document.c_metaTags.author : ""}`,
      },
    },

    {
      type: "meta",
      attributes: {
        name: "robots",
        content: `${document.c_metaTags.robot ? document.c_metaTags.robot : ""}`,
      },
    },

    {
      type: "link",
      attributes: {
        rel: "canonical",
        href:
        "https://master-conflict--spoils--dispersal-sbx-pgsdemo-com.sbx.preview.pagescdn.com/" +
          ` ${document.c_metaTags.c_canonicalURL ? document.c_metaTags.c_canonicalURL : ""}`,
      },
    },
    // og tags

    {
      type: "meta",
      attributes: {
        property: "og:url",
        content: "https://master-conflict--spoils--dispersal-sbx-pgsdemo-com.sbx.preview.pagescdn.com/" + currentUrl,
      },
    },

    {
      type: "meta",
      attributes: {
        property: "og:description",
        content: `${document.c_ogMetaTag.ogdescription ? document.c_ogMetaTag.ogdescription : ""
          }`,
      },
    },
    {
      type: "meta",
      attributes: {
        property: "og:title",
        content: `${document.c_ogMetaTag.ogtitle ? document.c_ogMetaTag.ogtitle : ""}`,
      },
    },
    {
      type: "meta",
      attributes: {
        property: "og:image",

        content: `${document.logo ? document.logo.image.url : ""}`,
      },
    },
    /// twitter tag

    // {
    //   type: "meta",
    //   attributes: {
    //     name: "twitter:card",
    //     content: "summary",
    //   },
    // },
    // {
    //   type: "meta",
    //   attributes: {
    //     name: "twitter:url",
    //     content: "https://master-conflict--spoils--dispersal-sbx-pgsdemo-com.sbx.preview.pagescdn.com/" + currentUrl,
    //   },
    // },
    // {
    //   type: "meta",
    //   attributes: {
    //     name: "twitter:title",
    //     content: document.c_twitterTag.twittertitle,
    //   },
    // },

    // {
    //   type: "meta",
    //   attributes: {
    //     name: "twitter:description",
    //     content: document.c_twitterTag.twitterdescription,
    //   },
    // },

    // {
    //   type: "meta",
    //   attributes: {
    //     name: "twitter:image",
    //     content: `${document.logo ? document.logo.image.url : ""}`,
    //   },
    // },
  ],
  };
};

const City: Template<TemplateRenderProps> = ({
  relativePrefixToRoot,
  path,
  document,
}) => {
  const {
    name,
    c_labels,
    c_addressRegionDisplayName,
    dm_directoryParents,
    dm_directoryChildren,
    yextDisplayCoordinate
    // c_globalData,
  } = document;
  var address;
  var c_companyrn;
  var c_footerLinks;
  var c_headerLinks1;
  var c_phoneNumber;

  var sortedChildren = dm_directoryChildren.sort(function (a: any, b: any) {
    var a = a.name;
    var b = b.name;
    return a < b ? -1 : a > b ? 1 : 0;
  });



  let slugString = "";
  
  document.dm_directoryParents.forEach((e: any) => {
    slugString += e.slug + "/";
  });
  const regionNames = new Intl.DisplayNames(["en"], { type: "region" });
  const childrenDivs = dm_directoryChildren.map((entity: any) => {
    // console.log(dm_directoryChildren, "dm_directoryChildren");

    var origin: any = null;
    if (entity.address.postalCode) {
      origin = entity.address.postalCode;
    } else if (entity.address.city) {
      origin = entity.address.city;
    } else if (entity.address.region) {
      origin = entity.address.region;
    } else {
      origin = entity.address.country;
    }
    let key: any = Object.keys(entity.hours)[0];

    return (
      <div className="location near-location">
      <div className="miles-with-title">
        <h3 className="">
          <a href={`/${entity.slug}.html`}>{entity.name}</a>
        </h3>
      </div>

      <Address address={entity.address} />
      <Phone phone={entity.mainPhone} />
      <div className="OpenCloseStatus icon-row">

        <div className="icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="19.106" height="19.106" viewBox="0 0 19.106 19.106">
              <path d="M170.493,161.44a9.053,9.053,0,1,0,9.053,9.053A9.058,9.058,0,0,0,170.493,161.44Zm.24.628a8.423,8.423,0,0,1,8.183,8.114h-1.45a.312.312,0,0,0,0,.624h1.45a8.423,8.423,0,0,1-8.183,8.112v-1.453h0a.312.312,0,0,0-.624,0v1.448a8.422,8.422,0,0,1-8.037-8.106h1.45a.312.312,0,0,0,0-.624h-1.45a8.423,8.423,0,0,1,8.037-8.109v1.448a.312.312,0,0,0,.624,0Zm-.311,3.14a.312.312,0,0,0-.313.313v5.434l-2.609,2.367a.313.313,0,0,0,.419.463l2.712-2.461h0a.312.312,0,0,0,.1-.231v-5.573a.312.312,0,0,0-.311-.313Z" transform="translate(-160.94 -160.94)" fill="#cc0c1f" stroke="#cc0c1f" stroke-width="1" fill-rule="evenodd" />
            </svg>
        </div>
        <OpenCloseStatus timezone={entity.timezone} hours={entity.hours} deliveryHours={{}}></OpenCloseStatus>
      </div>

      <div className="buttons">
        <div className="ctaBtn">
        {entity.yextDisplayCoordinate ? (
            <GetDirection
            label={c_labels}
              address={entity.address}
              latitude={entity.yextDisplayCoordinate?.latitude}
              longitude={entity.yextDisplayCoordinate?.longitude}
            />
          ) : (
            <GetDirection
            label={c_labels}
              address={entity}
              latitude={entity.yextDisplayCoordinate?.latitude}
              longitude={entity.yextDisplayCoordinate?.longitude}
            />
          )}
        </div>
        <div className="ctaBtn">
          <a
            className="button before-icon"
            href={`/${entity.slug}`}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="17.636"
              height="17.594"
              viewBox="0 0 17.636 17.594"
            >
              <g
                id="Group_56"
                data-name="Group 56"
                transform="translate(-2608.238 236.872)"
              >
                <path
                  id="Path_64"
                  data-name="Path 64"
                  d="M2621.436-219.279h-13.2v-16.757a1.447,1.447,0,0,1,1.49-.836c2.746.029,5.493,0,8.239.032a1.762,1.762,0,0,1,1.065.448c.926.851,1.815,1.744,2.669,2.666a1.737,1.737,0,0,1,.426,1c.057.98,0,1.966.033,2.948a1.533,1.533,0,0,0,.273.806,4.5,4.5,0,0,1,.569,4.6.782.782,0,0,0,.131.675c.683.738,1.414,1.432,2.122,2.148.9.909.825,1.568-.243,2.266h-.687l-2.15-1.986C2622.15-220.439,2622.233-219.672,2621.436-219.279Zm-3.322-16.863c-.286-.013-.488-.03-.69-.03-2.542,0-5.085.02-7.627-.015-.683-.009-.863.238-.86.881q.029,7.242,0,14.485c0,.654.2.876.871.87,3.344-.029,6.688,0,10.031-.018,1.839-.008,1.6.325,1.617-1.724,0-.527-.182-.685-.722-.462a4.428,4.428,0,0,1-5.525-1.577,1.122,1.122,0,0,0-.764-.4c-1.121-.043-2.245.007-3.365-.035a3.045,3.045,0,0,1-.905-.345,3.446,3.446,0,0,1,.935-.311c1.157-.038,2.316-.015,3.526-.015a4.511,4.511,0,0,1,1.623-4.924,4.462,4.462,0,0,1,5.146-.216v-2.836c-.739,0-1.426.02-2.11-.005-.818-.031-1.159-.384-1.177-1.194C2618.1-234.693,2618.115-235.378,2618.115-236.142Zm4.574,9.894a3.775,3.775,0,0,0-3.777-3.74,3.823,3.823,0,0,0-3.769,3.771,3.821,3.821,0,0,0,3.834,3.773A3.772,3.772,0,0,0,2622.689-226.248Zm-.958,3.467c.913.921,1.761,1.8,2.649,2.643.116.11.43.011.653.009-.008-.225.077-.537-.039-.66-.837-.885-1.715-1.732-2.59-2.6Zm-1.073-10.721-1.854-1.847a8.758,8.758,0,0,0,.022,1.314.734.734,0,0,0,.459.509A9.012,9.012,0,0,0,2620.658-233.5Z"
                  fill="#231f20"
                />
                <path
                  id="Path_65"
                  data-name="Path 65"
                  d="M2667.816-164.047c-1,0-2.008.016-3.011-.014-.2-.006-.4-.191-.6-.294.2-.126.407-.359.612-.362q2.977-.042,5.954,0c.213,0,.424.224.635.344-.217.109-.43.3-.651.312C2669.779-164.028,2668.8-164.047,2667.816-164.047Z"
                  transform="translate(-54.032 -69.638)"
                  fill="#231f20"
                />
                <path
                  id="Path_66"
                  data-name="Path 66"
                  d="M2709.52-94.767c-.753,0-1.508.023-2.26-.015-.2-.01-.39-.2-.585-.313.183-.119.365-.337.55-.341q2.328-.041,4.657,0c.175,0,.346.2.519.306-.184.121-.363.337-.553.347C2711.073-94.744,2710.3-94.767,2709.52-94.767Z"
                  transform="translate(-95.031 -136.523)"
                  fill="#231f20"
                />
                <path
                  id="Path_67"
                  data-name="Path 67"
                  d="M2666.084-26.562c.5,0,1-.026,1.5.016.15.013.284.216.426.333-.13.109-.257.311-.389.314q-1.569.038-3.139,0c-.131,0-.257-.2-.385-.31.139-.117.271-.323.419-.334C2665.035-26.587,2665.56-26.562,2666.084-26.562Z"
                  transform="translate(-53.925 -203.025)"
                  fill="#231f20"
                />
                <path
                  id="Path_68"
                  data-name="Path 68"
                  d="M2665.934,42.411c-.455,0-.913.027-1.364-.015-.156-.015-.3-.2-.444-.309.142-.119.281-.336.427-.34q1.432-.045,2.866,0c.139,0,.27.231.4.355-.152.1-.3.279-.457.292C2666.892,42.436,2666.412,42.411,2665.934,42.411Z"
                  transform="translate(-53.954 -268.956)"
                  fill="#231f20"
                />
                <path
                  id="Path_69"
                  data-name="Path 69"
                  d="M2665.783,180.509a12.024,12.024,0,0,1-1.294-.016c-.156-.017-.293-.214-.439-.33.145-.112.286-.315.435-.32q1.328-.045,2.658,0c.151.005.3.206.443.316-.146.116-.285.317-.441.333C2666.7,180.538,2666.238,180.509,2665.783,180.509Z"
                  transform="translate(-53.881 -402.274)"
                  fill="#231f20"
                />
                <path
                  id="Path_70"
                  data-name="Path 70"
                  d="M2830.271-12.755a2.988,2.988,0,0,1,3.047-2.962,3.024,3.024,0,0,1,2.984,3.045,3.029,3.029,0,0,1-3.068,2.964A2.99,2.99,0,0,1,2830.271-12.755Zm3.038,2.358a2.339,2.339,0,0,0,2.308-2.331,2.339,2.339,0,0,0-2.337-2.3,2.3,2.3,0,0,0-2.32,2.367A2.3,2.3,0,0,0,2833.309-10.4Z"
                  transform="translate(-214.35 -213.502)"
                  fill="#231f20"
                />
              </g>
            </svg>
            View Details
          </a>
        </div>
      </div>
    </div>
    );
  });

  function getDirectionUrl(entity: any) {
    var address_string = "";
    address_string =
      "Well Pharmacy" +
      "," +
      entity.address.line1 +
      "," +
      entity.address.line2 +
      "," +
      entity.address.city +
      "," +
      entity.address.region +
      "," +
      entity.address.postalCode +
      "," +
      regionNames.of(entity.address.countryCode);

    address_string = address_string.replace("undefined,", "");
    var origin: any = null;
    if (entity.address.city) {
      origin = entity.address.city;
    } else if (entity.address.region) {
      origin = entity.address.region;
    } else {
      origin = entity.address.country;
    }
    if (navigator.geolocation) {
      const error = (error: any) => {
       // var message_string =
       //   "Unable to determine your location. please share your location";
        // if (confirm(message_string) != true) {
        //   var getDirectionUrl =
        //     "https://www.google.com/maps/dir/?api=1&destination=" +
        //     entitiy.yextDisplayCoordinate.latitude +
        //     "," +
        //     entitiy.yextDisplayCoordinate.longitude +
        //     "&origin=" +
        //     origin;

        //   window.open(getDirectionUrl, "_blank");
        // } else {
        //   return false;
        // }
        var getDirectionUrl =
          "https://www.google.com/maps/dir/?api=1&destination=" +
          address_string +
          "&origin=" +
          origin;

        window.open(getDirectionUrl, "_blank");
      };
      navigator.geolocation.getCurrentPosition(
        function (position) {
          let currentLatitude = position.coords.latitude;
          let currentLongitude = position.coords.longitude;
          let getDirectionUrl =
            "https://www.google.com/maps/dir/?api=1&destination=" +
            address_string +
            "&origin=" +
            currentLatitude +
            "," +
            currentLongitude;
          window.open(getDirectionUrl, "_blank");
        },
        error,
        {
          timeout: 10000,
        }
      );
    }
  }
  return (
    <>
      <Header/>
        <BreadCrumbs
        name={name}
        parents={dm_directoryParents}
        baseUrl={relativePrefixToRoot}
        address={address}
      ></BreadCrumbs>

      <div className="hero">
         <img className="heroBanner" src={bannerImage} alt=""/>
         <div className="hero-content">
           <h1><strong>  Available loctions in {name} , {document.dm_directoryParents[2].name} , 
        {document.dm_directoryParents[1].name}{" "}</strong></h1>
         </div>
       </div>

      <div className="centered-container font-serif min-h-[550px]">
      <div className="directory-country nearby-sec">
        <div className="container">
          <div className="flex flex-wrap -mx-[15px]">{childrenDivs}</div>
        </div>
      </div>
      </div>
<Footer/>
  </>
  );
};
export default City;
