import * as React from "react";
import "../index.css";

import { GetPath, Template, TemplateProps, TemplateRenderProps, TemplateConfig, GetHeadConfig,
  HeadConfig } from "@yext/pages";
import { SearchHeadlessProvider, useSearchActions } from "@yext/search-headless-react";
import PageLayout from "../components/layouts/PageLayout";
import SearchLayout from "../components/locatorPage/SearchLayout";
import {  AnswerExperienceConfig  } from "../config/globalConfig";
import favicon from "../images/favicon.png";
import Banner from "../components/locationDetails/banner";
import banner from "../images/francepare1.png"



export const getPath: GetPath<TemplateProps> = () => {
  return `index.html`;

};
var currentUrl=''
export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({relativePrefixToRoot, path, document}): HeadConfig => {
  
  return {
    title: "France Pare Brise",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "link",
        attributes: {
          rel: "icon",
          type: "image/x-icon",
          href: favicon,
        },
      },
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
      {
        type: "meta",
        attributes: {
          name: "description",
          content: "France Pare Brise:mission of better sleep for all"
        },
      },

      {
        type: "meta",
        attributes: {
          name: "title",
          content: "France Pare Brise",
        },
      },
      {
        type: "meta",
        attributes: {
          name: "author",
          content: "France Pare Brise",
        },
      },

      {
        type: "meta",
        attributes: {
          name: "robots",
          content: "noindex, nofollow",
        },
      },

      {
        type: "link",
        attributes: {
          rel: "canonical",
          href:"https://master-unlovely--lurch--evoke-sbx-pgsdemo-com.sbx.preview.pagescdn.com/" +"index.html",
        },
      },
      // og tags

      {
        type: "meta",
        attributes: {
          property: "og:url",
          content:"https://master-unlovely--lurch--evoke-sbx-pgsdemo-com.sbx.preview.pagescdn.com/"  + currentUrl,
        },
      },

      {
        type: "meta",
        attributes: {
          property: "og:description",
          content:"France Pare Brise",
        },
      },
      {
        type: "meta",
        attributes: {
          property: "og:title",
          content: "France Pare Brise",
        },
      },
      {
        type: "meta",
        attributes: {
          property: "og:image",
          content:"https://www.franceparebrise.fr/sites/franceparebrise.fr/themes/custom/fpb/assets/img/logo.jpg",
        },
      },
      /// twitter tag

      {
        type: "meta",
        attributes: {
          name: "twitter:card",
          content: "summary",
        },
      },
      {
        type: "meta",
        attributes: {
          name: "twitter:url",
          content: "index.html"
        },
      },

      {
        type: "meta",
        attributes: {
          name: "twitter:description",
          content: "France Pare Brise",
        },
      },

      {
        type: "meta",
        attributes: {
          name: "twitter:image",
          // content:"http://file:///C:/Users/admin/Desktop/dream-site/src/images/",
        },
      },
    ],
  };
};

const locatorSearch: Template<TemplateRenderProps> = ({relativePrefixToRoot, path, document}) => {


const providerOptions: google.maps.MapOptions = {
  disableDefaultUI: true
}

return (
    <>
      <PageLayout>
  
        <SearchHeadlessProvider
            experienceKey={AnswerExperienceConfig.experienceKey}
            locale={AnswerExperienceConfig.locale}
            apiKey={AnswerExperienceConfig.apiKey}               
            verticalKey={AnswerExperienceConfig.verticalKey}
            experienceVersion={AnswerExperienceConfig.experienceVersion}
            sessionTrackingEnabled={AnswerExperienceConfig.sessionTrackingEnabled}  
            endpoints={AnswerExperienceConfig.endpoints}         
        >
          <div>
            <img src={banner} alt="" width="100%"/>
          </div>
          <div className="breadcrumb">
            <ul>
              <li>
                <a href="#" target="_self">
                  <svg className="fill-text-color" xmlns="http://www.w3.org/2000/svg" width="19.668" height="18.155" viewBox="0 0 19.668 18.155">
                    <path d="M10.94,22.655V16.6h4.539v6.052h4.614V13.577h2.95L13.209,4.5,3.375,13.577h2.95v9.077Z" transform="translate(-3.375 -4.5)"></path>
                  </svg>
                </a>
              </li>
              <li>Localisateur de magasin</li>
            </ul>
          </div>
           <SearchLayout/>           
        </SearchHeadlessProvider>   
      </PageLayout>
    </>
  );
};

export default locatorSearch;